version: "3.9"

services:

  portfolio-nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
      - static_data:/vol/static
    environment:
      - DOMAIN=${DOMAIN}

  portfolio-certbot:
    build:
      context: ./certbot
    command: echo "Skipping..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - portfolio-nginx

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
  static_data:
  data: 